---
downloads: ~/.ansible-downloads/

homebrew_installed_packages:
  - autoconf
  - bash-completion
  - chromedriver
  - doxygen
  - gettext
  - gifsicle
  - git
  - go
  - gpg
  - hub
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - wrk

homebrew_taps:
  - homebrew/core
  - caskroom/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - dropbox
  - firefox
  - google-chrome
  - handbrake
  - licecap
  - limechat
  - macvim
  - sequel-pro
  - skitch
  - slack
  - sublime-text
  - transmit
  - vagrant
  - virtualbox

dockitems_to_remove:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - System Preferences
  - Calendar

dockitems_to_add:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 1
  - name: Terminal
    path: "/Applications/Utilities/Terminal.app"
    pos: 2
  - name: Firefox
    path: "/Applications/Firefox.app"
    pos: 3
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 4
  - name: VirtualBox
    path: "/Applications/VirtualBox.app"
    pos: 5
