---
##
## CentOS
##
#- include: centos.yml
#  when: ansible_os_family == "CentOS"
#- include: centos5.yml
#  when: ansible_os_family == "CentOS" and ansible_os_family_major_version < '6'
#- include: centos6.yml
#  when: ansible_os_family == "CentOS" and ansible_os_family_major_version == '6'
#- include: centos7.yml
#  when: ansible_os_family == "CentOS" and ansible_os_family_major_version > '6'

##
## Debian
##
- include: debian_based.yml
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
- include: debian.yml
  when: ansible_os_family == "Debian"

##
## Ubuntu
##
- include: ubuntu.yml
  when:  ansible_os_family == "Ubuntu"

##
## Mac
##
- include: mac.yml
  when:  ansible_os_family == "MacOSX"
...
